[project]
name = "dev-shared"
dynamic = ["version"]
description = "dev-shared"
classifiers = [
    "Private :: Do Not Upload",
]
# https://devguide.python.org/versions/
# https://scientific-python.org/specs/spec-0000/
requires-python = ">=3.12"

dependencies = [
    "pytest",
    "pytest-mock",
    "pytest-cov",
    "poethepoet",
    "setuptools-scm",
    "ruff",
    "mypy",
]

[tool.ruff]
line-length = 79
